# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UITest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  pod 'SnapKit'

  # Pods for UITest

  target 'UITestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UITestUITests' do
    # Pods for testing
  end

end
